services:
  nginx:
    image: nginx:1.29.4-alpine-slim
    container_name: slave-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    networks: [elk-net]

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.5
    container_name: slave-filebeat
    user: root
    command: filebeat -e --strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - nginx-logs:/var/log/nginx
    depends_on: [nginx]
    networks: [elk-net]

  zabbix-agent-slave:
      image: zabbix/zabbix-agent2:alpine-latest
      container_name: zabbix-agent-slave
      environment:
        ZBX_SERVER_HOST: zabbix-server
        ZBX_SERVER_PORT: 10051
        ZBX_HOSTNAME: slave-host
      networks:
        elk-net:
          ipv4_address: 172.20.0.21

volumes:
  nginx-logs:

networks:
  elk-net:
    external: true
